const NAMESPACE = 'github/'

const G_GET_ALL_REPOS = 'getAllRepos'
const G_GET_REPO_URL = 'getRepoUrl'
const G_GET_REPO_OPEN_ISSUES = 'getRepoOpenIssues'
const G_GET_REPO_LANGUAGE = 'getRepoLanguage'
const G_GET_REPO_FIRST_COMMIT_DATE = 'getRepoFirstCommitDate'
const G_GET_REPO_LAST_COMMIT_DATE = 'getRepoLastCommitDate'
const G_GET_REPO_COMMITS_CROSSFILTER = 'getRepoCommitsCrossfilter'
const G_GET_REPO_COMMIT_COUNT = 'getRepoCommitCount'
const G_GET_REPO_TOP_COMMITTERS = 'getRepoTopCommitters'
const G_GET_REPO_BRANCH_NAMES = 'getBranchNames'
const G_GET_ALL_CONTENTS = 'getAllContents'
const M_CLEAR_STATE = 'clearState'
const M_REGISTER_REPOS = 'registerRepos'
const M_ADD_REPO_INFO = 'addRepoInfo'
const M_ADD_BRANCHES = 'addBranches'
const M_ADD_CHILD_COMMITS = 'addChildCommits'
const A_RESET_STATE = 'resetState'
const A_INIT_REPOS = 'initRepos'
const A_GATHER_REPO_INFO = 'gatherRepoInfo'
const A_GATHER_BRANCHES = 'gatherBranches'
const A_GATHER_CHILD_COMMITS = 'gatherChildCommits'
const A_ADD_ALL_CONTENTS = 'addAllContents'

const GITHUB_G_GET_ALL_REPOS = NAMESPACE + G_GET_ALL_REPOS
const GITHUB_G_GET_REPO_URL = NAMESPACE + G_GET_REPO_URL
const GITHUB_G_GET_REPO_OPEN_ISSUES = NAMESPACE + G_GET_REPO_OPEN_ISSUES
const GITHUB_G_GET_REPO_LANGUAGE = NAMESPACE + G_GET_REPO_LANGUAGE
const GITHUB_G_GET_REPO_FIRST_COMMIT_DATE = NAMESPACE + G_GET_REPO_FIRST_COMMIT_DATE
const GITHUB_G_GET_REPO_LAST_COMMIT_DATE = NAMESPACE + G_GET_REPO_LAST_COMMIT_DATE
const GITHUB_G_GET_REPO_COMMIT_COUNT = NAMESPACE + G_GET_REPO_COMMIT_COUNT
const GITHUB_G_GET_REPO_TOP_COMMITTERS = NAMESPACE + G_GET_REPO_TOP_COMMITTERS
const GITHUB_G_GET_ALL_CONTENTS = NAMESPACE + G_GET_ALL_CONTENTS
const GITHUB_A_RESET_STATE = NAMESPACE + A_RESET_STATE
const GITHUB_A_INIT_REPOS = NAMESPACE + A_INIT_REPOS
const GITHUB_A_ADD_ALL_CONTENTS = NAMESPACE + A_ADD_ALL_CONTENTS

const GITHUB_CACHE_FILENAME = '.githubRepoInfo.json'
const SAMPLE_GITHUB_CACHE_FILENAME = '.githubRepoInfo.json.sample'

module.exports = {
  G_GET_ALL_REPOS,
  G_GET_REPO_URL,
  G_GET_REPO_OPEN_ISSUES,
  G_GET_REPO_LANGUAGE,
  G_GET_REPO_FIRST_COMMIT_DATE,
  G_GET_REPO_LAST_COMMIT_DATE,
  G_GET_REPO_COMMITS_CROSSFILTER,
  G_GET_REPO_COMMIT_COUNT,
  G_GET_REPO_TOP_COMMITTERS,
  G_GET_REPO_BRANCH_NAMES,
  G_GET_ALL_CONTENTS,
  M_CLEAR_STATE,
  M_REGISTER_REPOS,
  M_ADD_REPO_INFO,
  M_ADD_BRANCHES,
  M_ADD_CHILD_COMMITS,
  A_RESET_STATE,
  A_INIT_REPOS,
  A_GATHER_REPO_INFO,
  A_GATHER_BRANCHES,
  A_GATHER_CHILD_COMMITS,
  A_ADD_ALL_CONTENTS,

  GITHUB_G_GET_ALL_REPOS,
  GITHUB_G_GET_REPO_URL,
  GITHUB_G_GET_REPO_OPEN_ISSUES,
  GITHUB_G_GET_REPO_LANGUAGE,
  GITHUB_G_GET_REPO_FIRST_COMMIT_DATE,
  GITHUB_G_GET_REPO_LAST_COMMIT_DATE,
  GITHUB_G_GET_REPO_COMMIT_COUNT,
  GITHUB_G_GET_REPO_TOP_COMMITTERS,
  GITHUB_G_GET_ALL_CONTENTS,
  GITHUB_A_RESET_STATE,
  GITHUB_A_INIT_REPOS,
  GITHUB_A_ADD_ALL_CONTENTS,

  GITHUB_CACHE_FILENAME,
  SAMPLE_GITHUB_CACHE_FILENAME,
}
