export const FAIRTRACKS_GITHUB_REPOS = [
  {
    title: 'The FAIRtracks.net web site',
    owner: 'fairtracks',
    name: 'fairtracks.net',
    branch: '',
    parentCommit: '',
  },
  // {
  //   title: 'TrackFind',
  //   owner: 'elixir-oslo',
  //   name: 'trackfind',
  //   branch: '',
  //   parentCommit: '',
  // },
  // {
  //   title: 'The Genomic HyperBrowser (TrackFind API Client)',
  //   owner: 'hyperbrowser',
  //   name: 'genomic-hyperbrowser',
  //   branch: 'ft_trackfindclient/elixir_delivery',
  //   parentCommit: '3ca800015becec1127ff10d58b6a8b8bb064130d',
  // },
  // {
  //   title: 'Track Hub Registry v1 (FAIRtracks branch)',
  //   owner: 'Ensembl',
  //   name: 'trackhub-registry',
  //   branch: 'fairtracks',
  //   parentCommit: 'ddd84f8c31d6bcb2496b5c7209ff329f6c976546',
  // },
  // {
  //   title: 'Track Hub Registry v2 (Second implementation of Trackhub Registry)',
  //   owner: 'Ensembl',
  //   name: 'thr',
  //   branch: '',
  //   parentCommit: '',
  // },
  {
    title: 'FAIRtracks validator',
    owner: 'fairtracks',
    name: 'fairtracks_validator',
    branch: '',
    parentCommit: '',
  },
  {
    title: 'FAIRtracks augmentation service',
    owner: 'fairtracks',
    name: 'fairtracks_augment',
    branch: '',
    parentCommit: 'c426864deb125459ea08d2151717e78da2b4a91f', // TODO: Remove, only for dev
  },
  {
    title: 'FAIRtracks JSON-to-GSuite converter',
    owner: 'fairtracks',
    name: 'fairtracks_json_to_gsuite',
    branch: '',
    parentCommit: '',
  },
  {
    title: 'uniFAIR (under development)',
    owner: 'fairtracks',
    name: 'unifair',
    branch: '',
    parentCommit: '',
  },
]
